-- Generated by Lava 2000

use work.all;

entity
  adder3
is
port
  -- clock
  ( clk : in bit

  -- inputs
  ; a1 : in bit
  ; a2 : in bit
  ; a3 : in bit
  ; b1 : in bit
  ; b2 : in bit
  ; b3 : in bit

  -- outputs
  ; s1 : out bit
  ; s2 : out bit
  ; s3 : out bit
  ; co : out bit
  );
end entity adder3;

architecture
  structural
of
  adder3
is
  signal w1 : bit;
  signal w2 : bit;
  signal w3 : bit;
  signal w4 : bit;
  signal w5 : bit;
  signal w6 : bit;
  signal w7 : bit;
  signal w8 : bit;
  signal w9 : bit;
  signal w10 : bit;
  signal w11 : bit;
  signal w12 : bit;
  signal w13 : bit;
  signal w14 : bit;
  signal w15 : bit;
  signal w16 : bit;
  signal w17 : bit;
  signal w18 : bit;
  signal w19 : bit;
  signal w20 : bit;
  signal w21 : bit;
  signal w22 : bit;
begin
  c_w3      : entity id    port map (clk, a1, w3);
  c_w4      : entity id    port map (clk, b1, w4);
  c_w2      : entity xor2  port map (clk, w3, w4, w2);
  c_w5      : entity gnd   port map (clk, w5);
  c_w1      : entity xor2  port map (clk, w2, w5, w1);
  c_w8      : entity id    port map (clk, a2, w8);
  c_w9      : entity id    port map (clk, b2, w9);
  c_w7      : entity xor2  port map (clk, w8, w9, w7);
  c_w11     : entity and2  port map (clk, w3, w4, w11);
  c_w12     : entity and2  port map (clk, w2, w5, w12);
  c_w10     : entity xor2  port map (clk, w11, w12, w10);
  c_w6      : entity xor2  port map (clk, w7, w10, w6);
  c_w15     : entity id    port map (clk, a3, w15);
  c_w16     : entity id    port map (clk, b3, w16);
  c_w14     : entity xor2  port map (clk, w15, w16, w14);
  c_w18     : entity and2  port map (clk, w8, w9, w18);
  c_w19     : entity and2  port map (clk, w7, w10, w19);
  c_w17     : entity xor2  port map (clk, w18, w19, w17);
  c_w13     : entity xor2  port map (clk, w14, w17, w13);
  c_w21     : entity and2  port map (clk, w15, w16, w21);
  c_w22     : entity and2  port map (clk, w14, w17, w22);
  c_w20     : entity xor2  port map (clk, w21, w22, w20);

  -- naming outputs
  c_s1      : entity id    port map (clk, w1, s1);
  c_s2      : entity id    port map (clk, w6, s2);
  c_s3      : entity id    port map (clk, w13, s3);
  c_co      : entity id    port map (clk, w20, co);
end structural;
