-- Generated by Lava 2000

use work.all;

entity
  Chapter3/bitSubber
is
port
  -- clock
  ( clk : in bit

  -- inputs
  ; b : in bit
  ; bs_0 : in bit
  ; bs_1 : in bit
  ; bs_2 : in bit
  ; bs_3 : in bit

  -- outputs
  ; rs_0 : out bit
  ; rs_1 : out bit
  ; rs_2 : out bit
  ; rs_3 : out bit
  );
end entity Chapter3/bitSubber;

architecture
  structural
of
  Chapter3/bitSubber
is
  signal w1 : bit;
begin
  c_w1      : entity gnd   port map (clk, w1);

  -- naming outputs
  c_rs_0    : entity id    port map (clk, w1, rs_0);
  c_rs_1    : entity id    port map (clk, w1, rs_1);
  c_rs_2    : entity id    port map (clk, w1, rs_2);
  c_rs_3    : entity id    port map (clk, w1, rs_3);
end structural;
