-- Automatically generated by ForSyDe
library forsyde;
library ieee;
use forsyde.types.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;


package types is

     type tup_6_std_logic_std_logic_std_logic_std_logic_std_logic_std_logic is
          record tup_1 : std_logic;
                 tup_2 : std_logic;
                 tup_3 : std_logic;
                 tup_4 : std_logic;
                 tup_5 : std_logic;
                 tup_6 : std_logic;
          end record;
     
     type tup_2_std_logic_std_logic is
          record tup_1 : std_logic;
                 tup_2 : std_logic;
          end record;
     
     type tup_2_int16_tup_2_std_logic_std_logic is
          record tup_1 : int16;
                 tup_2 : tup_2_std_logic_std_logic;
          end record;
     
     function default return tup_6_std_logic_std_logic_std_logic_std_logic_std_logic_std_logic;
     
     function show (tup : tup_6_std_logic_std_logic_std_logic_std_logic_std_logic_std_logic)
                   return string;
     
     function default return tup_2_std_logic_std_logic;
     
     function show (tup : tup_2_std_logic_std_logic)
                   return string;
     
     function default return tup_2_int16_tup_2_std_logic_std_logic;
     
     function show (tup : tup_2_int16_tup_2_std_logic_std_logic)
                   return string;

end package types;


package body types is

     function default return tup_6_std_logic_std_logic_std_logic_std_logic_std_logic_std_logic is
     begin
          return (default, default, default, default, default, default);
     end;
     
     function show (tup : tup_6_std_logic_std_logic_std_logic_std_logic_std_logic_std_logic)
                   return string is
     begin
          return '(' &
                 (show(tup.tup_1) & ',' &
                  (show(tup.tup_2) & ',' &
                   (show(tup.tup_3) & ',' &
                    (show(tup.tup_4) & ',' &
                     (show(tup.tup_5) & ',' & show(tup.tup_6)))))) &
                 ')';
     end;
     
     function default return tup_2_std_logic_std_logic is
     begin
          return (default, default);
     end;
     
     function show (tup : tup_2_std_logic_std_logic)
                   return string is
     begin
          return '(' & (show(tup.tup_1) & ',' & show(tup.tup_2)) & ')';
     end;
     
     function default return tup_2_int16_tup_2_std_logic_std_logic is
     begin
          return (default, default);
     end;
     
     function show (tup : tup_2_int16_tup_2_std_logic_std_logic)
                   return string is
     begin
          return '(' & (show(tup.tup_1) & ',' & show(tup.tup_2)) & ')';
     end;

end package body types;
