-- Generated by Lava 2000

use work.all;

entity
  fullAdd
is
port
  -- clock
  ( clk : in bit

  -- inputs
  ; carryIn : in bit
  ; a : in bit
  ; b : in bit

  -- outputs
  ; sum : out bit
  ; carryOut : out bit
  );
end entity fullAdd;

architecture
  structural
of
  fullAdd
is
  signal w1 : bit;
  signal w2 : bit;
  signal w3 : bit;
  signal w4 : bit;
  signal w5 : bit;
  signal w6 : bit;
  signal w7 : bit;
  signal w8 : bit;
begin
  c_w3      : entity id    port map (clk, a, w3);
  c_w4      : entity id    port map (clk, b, w4);
  c_w2      : entity xor2  port map (clk, w3, w4, w2);
  c_w5      : entity id    port map (clk, carryIn, w5);
  c_w1      : entity xor2  port map (clk, w2, w5, w1);
  c_w7      : entity and2  port map (clk, w3, w4, w7);
  c_w8      : entity and2  port map (clk, w2, w5, w8);
  c_w6      : entity xor2  port map (clk, w7, w8, w6);

  -- naming outputs
  c_sum     : entity id    port map (clk, w1, sum);
  c_carryOut : entity id    port map (clk, w6, carryOut);
end structural;
