-- Automatically generated by ForSyDe
library forsyde;
library ieee;
use forsyde.types.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library addFour_lib;
use addFour_lib.types.all;


entity \addFour\ is
     port (\in1\ : in int16;
           \out1\ : out int16);
end entity \addFour\;


architecture synthesizable of \addFour\ is
     signal \plus1_4_out1\ : int16;
     signal \plus1_3_out1\ : int16;
     signal \plus1_2_out1\ : int16;
     signal \plus1_1_out1\ : int16;
begin
     \plus1_4\ : entity work.\plus1\
                      port map (\inSig\ => \in1\,
                                \outSig\ => \plus1_4_out1\);
     
     \plus1_3\ : entity work.\plus1\
                      port map (\inSig\ => \plus1_4_out1\,
                                \outSig\ => \plus1_3_out1\);
     
     \plus1_2\ : entity work.\plus1\
                      port map (\inSig\ => \plus1_3_out1\,
                                \outSig\ => \plus1_2_out1\);
     
     \plus1_1\ : entity work.\plus1\
                      port map (\inSig\ => \plus1_2_out1\,
                                \outSig\ => \plus1_1_out1\);
     
     \out1\ <= \plus1_1_out1\;
end architecture synthesizable;
