-- Automatically generated by ForSyDe
library forsyde;
library ieee;
use forsyde.types.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library addFour_lib;
use addFour_lib.types.all;


entity \plus1\ is
     port (\inSig\ : in int16;
           \outSig\ : out int16);
end entity \plus1\;


architecture synthesizable of \plus1\ is
     signal \plus1Proc_out\ : int16;
begin
     \plus1Proc\ : block
          port (\plus1Proc_in1\ : in int16;
                \plus1Proc_out\ : out int16);
          port map (\plus1Proc_in1\ => \inSig\,
                    \plus1Proc_out\ => \plus1Proc_out\);
          function \addOnef\ (\n_0\ : int16)
                             return int16 is
          begin
               return \n_0\ + 1;
          end;
     begin
          \plus1Proc_out\ <= \addOnef\(\n_0\ => \inSig\);
     end block \plus1Proc\;
     
     \outSig\ <= \plus1Proc_out\;
end architecture synthesizable;
